"""initial migration

Revision ID: 361204bcc0c9
Revises: 
Create Date: 2026-04-09 23:30:33.847140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361204bcc0c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We only keep the changes to the 'users' table to avoid deleting unrelated tables
    op.add_column('users', sa.Column('face_image', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'face_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'face_image')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
