"""add cascade delete to attendance

Revision ID: 6a6f8f3e953d
Revises: bf3001c83c8b
Create Date: 2026-04-15 10:57:22.686797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6f8f3e953d'
down_revision: Union[str, Sequence[str], None] = 'bf3001c83c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_user_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_user_id_fkey'), 'attendance', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
