"""add status column to attendance

Revision ID: b1597fb939c7
Revises: 361204bcc0c9
Create Date: 2026-04-10 12:53:32.425683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1597fb939c7'
down_revision: Union[str, Sequence[str], None] = '361204bcc0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_ids')
    op.drop_index(op.f('password_resets_email_index'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_table('failed_jobs')
    op.drop_table('class_session')
    op.drop_table('migrations')
    op.drop_table('school_years')
    op.drop_table('classroom')
    op.drop_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_table('class_attendance')
    op.drop_index(op.f('reset_password_email_index'), table_name='reset_password')
    op.drop_table('reset_password')
    op.add_column('attendance', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'status')
    op.create_table('reset_password',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reset_password_pkey'))
    )
    op.create_index(op.f('reset_password_email_index'), 'reset_password', ['email'], unique=False)
    op.create_table('class_attendance',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('student_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attendance_day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('class_attendance_pkey'))
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tokenable_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('abilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_access_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('personal_access_tokens_token_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False)
    op.create_table('classroom',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_prof', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_room', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_section', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_school_year', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_days', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_start_time', postgresql.TIME(precision=0), autoincrement=False, nullable=False),
    sa.Column('class_end_time', postgresql.TIME(precision=0), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('classroom_pkey'))
    )
    op.create_table('school_years',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('year', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('school_years_pkey')),
    sa.UniqueConstraint('year', name=op.f('school_years_year_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('migrations_pkey'))
    )
    op.create_table('class_session',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('class_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('class_start_time', postgresql.TIME(precision=0), autoincrement=False, nullable=False),
    sa.Column('class_end_time', postgresql.TIME(precision=0), autoincrement=False, nullable=False),
    sa.Column('class_late', postgresql.TIME(precision=0), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('class_session_pkey'))
    )
    op.create_table('failed_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('connection', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_jobs_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('failed_jobs_uuid_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('password_resets',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('password_resets_email_index'), 'password_resets', ['email'], unique=False)
    op.create_table('verification_ids',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_ids_pkey'))
    )
    # ### end Alembic commands ###
