"""add_face_embedding_to_user

Revision ID: bf3001c83c8b
Revises: d7b9b2f1968e
Create Date: 2026-04-14 14:40:36.448787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3001c83c8b'
down_revision: Union[str, Sequence[str], None] = 'd7b9b2f1968e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embedding')
    # ### end Alembic commands ###
