"""add location_name to attendance

Revision ID: d7b9b2f1968e
Revises: a861fd2aba22
Create Date: 2026-04-13 20:19:22.876328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b9b2f1968e'
down_revision: Union[str, Sequence[str], None] = 'a861fd2aba22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('location_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'location_name')
    # ### end Alembic commands ###
